@startuml kubernetes

footer Kubernetes Service expansion
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 10


' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesSvc.puml
!includeurl KubernetesPuml/OSS/KubernetesIng.puml
!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesRs.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml
!includeurl KubernetesPuml/OSS/KubernetesHpa.puml

left to right direction

' Service_Boundary(redisns, Redis Service) {
'     KubernetesSvc(svcRedis2, "Redis svc", "")
'     KubernetesDeploy(deployRedis, "Deployment", "")
'     KubernetesRs(rsRedis, "ReplicaSet", " ")
'     KubernetesPod(podRedis1, "Master", "")
'     KubernetesPod(podRedis2, "Slave 1", "")
'     KubernetesPod(podRedis3, "Slave 2", "")
' }
' Rel_U(deployRedis, rsRedis, " ")
' Rel_U(rsRedis, podRedis1, " ")
' Rel_U(rsRedis, podRedis2, " ")
' Rel_U(rsRedis, podRedis3, " ")
' Rel(svcRedis2,podRedis1, " ")
' Rel(svcRedis2,podRedis2, " ")
' Rel(svcRedis2,podRedis3, " ")

Service_Boundary(msSqlns, MS SQL Service) {
    KubernetesSvc(svcMsSql2, "DB svc", "")
    KubernetesDeploy(deployMsSql, "Deployment", "")
    KubernetesRs(rsMsSql, "ReplicaSet", " ")
    KubernetesPod(podMsSql1, "MS SQL", "")
}
Rel_U(deployMsSql, rsMsSql, " ")
Rel_U(rsMsSql, podMsSql1, " ")
Rel(svcMsSql2,podMsSql1, " ")

Service_Boundary(hivens, Hive Service) {
    KubernetesSvc(svcHive2, "Hive svc", "")
    KubernetesDeploy(deployHive, "Deployment", "")
    KubernetesRs(rsHive, "ReplicaSet", " ")
    KubernetesPod(podHive1, "Hive 1", "")
    KubernetesPod(podHive2, "Hive 2", "")
}
Rel_U(deployHive, rsHive, " ")
Rel_U(rsHive, podHive1, " ")
Rel_U(rsHive, podHive2, " ")
Rel(svcHive2,podHive1, " ")
Rel(svcHive2,podHive2, " ")



@enduml