@startuml


skinparam actorStyle Hollow

actor Device #Green
participant "Hive MQTT Broker" as Hive #Yellow
participant Backend #white

Device -> Hive: getPairingCode(deviceId)
Hive --> Backend++: receiveMessage(getPairingCode(deviceId))
Hive --> Device: receiveMessage(pairingCode)



@enduml