@startuml kubernetes

footer Kubernetes Components for Device Flow
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 10


' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesSvc.puml
!includeurl KubernetesPuml/OSS/KubernetesIng.puml
!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesRs.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml
!includeurl KubernetesPuml/OSS/KubernetesHpa.puml

' actor "Device" as device
left to right direction

' Kubernetes Components
Cluster_Boundary(cluster, "IOTProject Kubernetes Cluster (Device Related)") {
    Namespace_Boundary(ns, "Production") {
        KubernetesIng(ingWeb, "iotingest.[...].dev", "")
        Service_Boundary(displayDbBnd, " ") {
            KubernetesSvc(svcDb, "Database", "")
        }

        Service_Boundary(displayHiveBnd, " ") {
            KubernetesSvc(svcMqtt, "Hive Cluster", "")
        }
        KubernetesPod(podApi1, "Web Server", "")
        KubernetesDeploy(deployApi, "Deployment", "")
        KubernetesRs(rsApi, "ReplicaSet", " ")
        ' KubernetesPod(podMsq1, "hivemq1", "")
    }
}

Rel(ingWeb,svcMqtt, " ")
Rel_U(podApi1,svcMqtt, " ")
Rel(podApi1,svcDb, " ")
Rel_L(deployApi, rsApi, " ")
Rel_L(rsApi, podApi1, " ")
' Rel(svcMqtt,podMsq1, " ")
' Rel(device,ingIngest, " ")
' Rel(ingIngest,svcMqtt, " ")
@enduml